version: '3'
services:
  dbt-bq-dtc:
    build:
      context: .
      target: dbt-bigquery
    image: dbt/bigquery
    volumes:
      - /home/<USER>/dbt_noaa_zoom:/usr/app
      - ~/.dbt/:/root/.dbt/
      - /home/<USER>/.ssh/.google/credentials/google_credentials.json:/.google/credentials/google_credentials.json
    network_mode: host
    
