dtc_noaa_zoom:
  outputs:
    dev:
      dataset: noaa_isd_analytics
      fixed_retries: 1
      keyfile: /home/<USER>/.ssh/.google/credentials/google_credentials.json
      location: US
      method: service-account
      priority: interactive
      project: dtc-de-zoom-camp
      threads: 10
      timeout_seconds: 300
      type: bigquery
  target: dev
